apiVersion: v1
kind: Service
metadata:
  name: wifi-coverage-analysis
  labels:
    app: wifi-coverage-analysis
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: wifi-coverage-analysis 