version: '3.8'

services:
  web:
    build: .
    container_name: wifi_coverage_analysis
    volumes:
      - ./vippfinaldata:/app
      - ./data:/app/data
      - ./plots:/app/plots
      - ./models:/app/models
      - ./output:/app/output
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped 